apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-job-ttl-
  annotations:
    ttl: "30 minutes"
spec:
  template:
    spec:
      containers:
      - name: example
        image: centos
        command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 0
